# Generated by Django 5.0 on 2023-12-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=22, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
